directive @constrains(minLength: Int, maxLength: Int) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

type Query {

  continent(code: String!): Continent!
  countries: [Country!]!
  country(code: String!): Country!
  languages: [Language]!
  language(code: String!): Language!
}

type Mutation {
  addCountry(input: CountryInput!): Country!
  updateCountry(code: String!, input: CountryInput!): Country!
  deleteCountry(code: String!): Boolean!

  addState(input: StateInput!): State!
  deleteState(code: String!): Boolean!

  addLanguage(input: LanguageInput!): Language!
  deleteLanguage(code: String!): Boolean!
}

type Continent {
  code: String!
  name: String!

}

type Country {
  code: String! @constrains(minLength: 2, maxLength: 10)
  name: String! @constrains(minLength: 2, maxLength: 25)
  native: String
  phone: String!
  continent: Continent
  emoji:String
  emojiU: String  
  languages: [Language]

  
  }

type State {
 
  name: String!
  country: Country!
}

type Language {
  code: String!
  name: String!
  native: String
  rtl: Int!
 
}

input CountryInput {
  code: String! @constrains(minLength: 2, maxLength: 5)
  name: String! @constrains(minLength: 2, maxLength: 25)
  native: String
  phone:String!
  continent: String!
  currency: String
  emoji:String
  emojiU:String
 
}

input StateInput {
  code: String!
  name: String!

}

input LanguageInput {
  code: String!
  name: String!
  native: String!
  rtl: Int
  country: String!
}
